---
- hosts: RHELKControlplane
  become: yes
  become_user: root
  vars_files:
  - vars/mastervariables
  roles:
  - base
  - controlplane

- hosts: RHELKMaster
  become: yes
  become_user: root
  vars_files:
  - vars/mastervariables
  roles:
  - base
  - master 
  
- hosts: RHELKWorker
  become: yes
  become_user: root
  vars_files:
  - vars/workervariables
  roles:
  - base
  - worker
